### ISSUE TITLE
AN1200.57 documentation states wrong link

### ISSUE THREAD

**Issue by ghost** [Lora-net/radio_firmware_images#1]
Hi,

The _Application Note: LR1110: Upgrade of the Program Memory_ states:

> Semtech posts versioned, signed, and encrypted firmware images at the following link: https://github.com/Lora-net/fw_images/lr1110/modem/.

Following that you end up with GitHub's 404 message.

It is quite easy to find nonetheless, though I think the documentation should be updated. (Some of the other links are also broken, which might be something you may wish to look into)

Thanks

**Comment by mverdy** [comment]
Hi @vytvir,

Thanks for reporting. We will propagate this issue to fix the doc.

For future reference, the broken link should be replaced with https://github.com/Lora-net/radio_firmware_images/tree/master/lr1110/modem.
