### ISSUE TITLE
LR1110 transceiver firmware v3.4 hangs on WiFiReadResults with Basic format

### ISSUE THREAD

**Issue by jamesl-dm** [Lora-net/radio_firmware_images#3]
When scanning WiFi with:
  03 01 04 3F FF 02 07 00 96 00 00

If I read back the results with full format it works:
  03 06 00 07 01

But if I read back the results with basic format:
  03 06 00 07 04

Then it works on v3.3, but hangs on v3.4, with the BUSY pin staying high indefinitely.

**Comment by matthieuantoine** [comment]
@jamesl-dm, thanks for reporting this issue! We found the root cause. A new firmware version will be available shortly.

**Comment by matthieuantoine** [comment]
This is now fixed in firmware 0x0305.
