### ISSUE TITLE
LR1110 modem firmware event pin io-levels / drive strength issue

### ISSUE THREAD

**Issue by ncasaril** [Lora-net/radio_firmware_images#4]
The LR1110 modem firmware doesn't give proper event signals on DIO9 in a 3.3V system. 

The captures have been done with a Saleae 16 logic analyser (using both analog and digital inputs). All events have been generated from a wifi scan which results in networks found both using the transceiver and the modem firmwares. 

First capture shows the modem-e firmware for a wifi scan. The spi command to start the wifi scan can be seen as the short dip on the CSN channel in the left corner. After about 1.5s the BUSY goes high and the EVENT / IRQ goes from 0V to 0.6V. 0.6V is not enough to trigger the interrupt on the mcu. 

![20210217_wifi_scan_modem_e](https://user-images.githubusercontent.com/14293132/108139938-d4e11880-710c-11eb-9de0-bc414f864852.png)

I've used the same hardware module running the transceiver firmware as a control. The capture below shows the resulting interrupt / event generated from a wifi scan. Again, the spi command to start the wifi scan can be seen as the short dip on CSN. After about 1s the BUSY goes high as does EVENT / IRQ with a proper voltage level around 3.4V. 

![20210217_wifi_scan_transceiver_evnt (2)](https://user-images.githubusercontent.com/14293132/108140805-3bb30180-710e-11eb-9b28-d12adce8a084.png)

The initialisation of the modem firmware can be seen below (excluding crc bytes). Note that the firmware
makes sure to flush the event buffer at the end of initialisation. 

```
      usec flags  cmd                             desc                       data
-------------------------------------------------------------------------------------------
        0   RST
  1102142     W   011001                         SY|SET_REGMODE
  1104736     W   01120F00010302000408           SY|SET_DIO_RFSW
  1107452     W   0117060005DC                   SY|SET_TCXO_MODE
  1110076     W   011605                         SY|CONFIG_LFCLK
  1118041     W   063602                         MM|MANAGE_RF_OUTPUT
  1120666     R   060F                           MM|GET_EUI               8 0016C001F0008B10
## Event queue flush
  1122711     R   0633                           MM|GET_EVENT_SIZE        2 0004
  1124725     R   0600                           MM|GET_EVENT             4 00000033
  1126770     R   0633                           MM|GET_EVENT_SIZE        2 0002
  1128753     R   0600                           MM|GET_EVENT             2 FF00
## Wifi scan start
 20966491     W   030401                         WI|HW_DEBARKER
 20969085     W   0330013FFF01040200460004       WI|WIFI_PSV_SCAN
```

**Comment by matthieuantoine** [comment]
Can you please share some information about your setup?

On our side, based on the LR1110 EVK, we cannot reproduce this issue:

![image](https://user-images.githubusercontent.com/44699865/108231984-99f9d780-7142-11eb-87fc-000c8aa74202.png)

**Comment by ncasaril** [comment]
Thanks for looking into it. On our board there's a 10k pull-down on the interrupt line. Removing this resistor allows the interrupt line to reach a digital one with the modem-e firmware also. 

Still, I think you should have the same drive-strength in transceiver mode as in modem mode. Could it be that rather than driving the IRQ pin high from the modem firmware you're just doing a pull-up? After all the transceiver firmware had no problem driving the IRQ pin high.

**Comment by matthieuantoine** [comment]
This difference comes from the fact that the modem goes back to sleep mode as often as possible, so the pull-up method is the only one available in this case.

**Comment by ncasaril** [comment]
Understood! Closing this issue.
